server:
  port: 8100
spring:
  application:
    name: redbook-service-comment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.1:8848
  data:
    mongodb:
      host: localhost
      port: 27017
      database: redbook
      username: root
      password: root
      authentication-database: admin


